# Generated by Django 5.1.6 on 2026-03-07 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('operator', models.CharField(max_length=100)),
                ('bus', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('plateNumber', models.CharField(max_length=20)),
                ('routeCode', models.CharField(max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(default=90)),
                ('status', models.CharField(default='inactive', max_length=20)),
                ('year', models.IntegerField()),
                ('busLoginId', models.CharField(max_length=50, unique=True)),
                ('busLoginCode', models.CharField(max_length=50)),
            ],
        ),
    ]
